### ISSUE TITLE
ConcurrentModificationException on Planet leaving system

### ISSUE THREAD

**Issue by jeyj0** [InfoSimulators/GravitySimulation#7]
When a planet leaves the system in a simulation started by a GeneticTrainer, there is a ConcurrentModificationException occuring. 

This can be reproduced by running Main at current development status. 

This issue occurs because of bad List handling, probably when removing the planet from a List.

Since this issue is in @Julisep 's code, you are assigned to solve it.

![screenshot_20170226_000610](https://cloud.githubusercontent.com/assets/12881718/23335585/3dff4540-fbb8-11e6-81d2-5613eec1215c.png)

**Comment by KeineLimonade** [comment]
Should work now.

**Comment by jeyj0** [comment]
No, it does not. Try executing yourself.

Read up about the exception and you'll see why it occurs :)

**Comment by KeineLimonade** [comment]
Now it must work.
